version: "3.0"
services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
    - postgre_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine3.19

  job-runner:
    build: ./job-runner
      
volumes:
  postgre_data:
