version: "3.0"
services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
    - postgre_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine3.19
    ports:
    - "6379:6379"

  job-runner:
    build: ./job-runner
    volumes:
    - ./job-runner/cache:/root/.cache/huggingface/
    - ./job-runner/output:/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      
volumes:
  postgre_data:
